# Tutorial 2

## Numpy

### Pergunta 1

1. Use a função `arange` de numpy para criar um vetor chamado `my_array` com a sequencia de números desde zero até 24.

2. Use a função `reshape` para redimensionar o vetor de tal forma que fique com seis filas e cinco colunas. Que acontece? Qual é a relação entre número de elementos e a dimensão duma matrix bi-dimensional?

3. Sendo que temos 24 elementos, identifique duas combinações de dimensões que permitam redimensionar este vector em forma de matriz.

In [ ]:
import numpy as np


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Pergunta 2

Considere a função da similaridade de coseno com a qual trabalhamos ontem:

$$
  cos(v1, v2) = \frac{v1 . v2}{\lVert v1 \rVert \times \lVert v2 \rVert}
$$  

Investigar o uso das funções `linalg.norm` e `dot` dentro de Numpy para re-escrever a função sem usar qualquer `for` loop.

In [ ]:
import numpy as np
v1 = [1,2,3,4]
v2 = [3,2,5,4]

# resposta aqui

38
40.24922359499622


0.9441175904999112

## Pergunta 3

$$\begin{bmatrix} 
1 & 2 & 1 & 7 \\ 
3 & 0 & 1 & 8 \\ 
0 & 2 & 4 & 9 \\ 
2 & 2 & 5 & 5
\end{bmatrix}$$

1. Criar esta matriz em numpy
2. Slice a primeira coluna inteira
3. Slice a primeira coluna mas so as filas 2 e 3
4. Slice os quatro elementos no centro da matriz
5. Slice a sub-matriz dos quatro elementos no canto inferior direito, sem usar o tamanho da matriz
6. Slice a sub-matriz dos quatro elementos no canto superior direito, sem usar o tamanho da matriz


In [ ]:
# Pergunta 3.1: criação da matriz como objeto de numpy


# Pergunta 3.2: primeira coluna, 
# não há necessidade de saber as dimensões da matriz


# Pergunta 3.3: slice primeira coluna mas so as filas 2 e 3
# não há necessidade de saber as dimensões da matriz


# Pergunta 3.4: slice os quatro elementos no centro da matriz
# este slice usa o conhecimento do tamanho da matriz
# no caso geral será necessário escrever uma função que determine
# o slice


# Pergunta 3.5: slice a sub-matriz dos quatro elementos no canto inferior 
# direito, sem usar o tamanho da matriz.
# esta versão não cumpre o requerimento, porque conta desde o início da matriz
# e portanto está a usar informação do tamanho da mesma para atingir o
# objetivo



# Pergunta 3.5: slice a sub-matriz dos quatro elementos no canto inferior 
# direito, sem usar o tamanho da matriz.
# esta versão sim cumpre o requerimento, porque define o slice desde o fim
# da matriz


# Pergunta 3.6: slice a sub-matriz dos quatro elementos no canto inferior 
# direito, sem usar o tamanho da matriz.

# esta versão usa informação do tamanho da matriz para definir a seleção
# de colunas


# esta versão cumpre o requerimento


# esta versão cumpre o requerimento


first column: 
 [1 3 0 2] 

first column, rows 2 and 3: 
 [3 0] 

centre: 
 [[0 1]
 [2 4]] 

bottom right: 
 [[4 9]
 [5 5]] 

top right: 
 [[1 7]
 [1 8]] 

top right: 
 [[1 7]
 [1 8]] 

bottom right: 
 [[4 9]
 [5 5]] 

top right: 
 [[1 7]
 [1 8]] 



## Pergunta 4

Dado o ficheiro json de teste, carregue o mesmo num Pandas dataframe, e mantenha unicamente as seguintes colunas:

1. user_id
2. institution_id
3. age
4. gender

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

# o vosso path para o ficheiro poderá ser diferente ao meu

path = '/content/drive/MyDrive/Colab Notebooks/A2_user_details.json'



user_id  institution_id  age  gender
0      1128               9   18    MALE
1      1050               7   16  FEMALE
2       986               1   17  FEMALE
3       987               1   16  FEMALE
4       988               1   16  FEMALE
..      ...             ...  ...     ...
93     1841               2   17  FEMALE
94     1855               2   17  FEMALE
95     1096               7   20    MALE
96     1878               2   17    MALE
97     2875               4   16  FEMALE

[98 rows x 4 columns]

## Pergunta 5

### P5.1
Selecione os `user_id` das raparigas com idade 17 anos ou mais e guarde numa variáevel `fids`. Esta variável, é um `Series` ou um `DataFrame`

### P5.2
Selecione os `gender` dos estudantes das escolas 1 e 2 com maiores de 17 anos

### p5.3
Adicione uma columa "scores" com valores aleatórios entre 10 e 20 para todos os alunos no dataframe

In [ ]:

# P5.1


2      986
6      990
8      992
17    1005
19    1007
23    1112
26    1032
28    1151
29    1839
30    1035
36    3080
37    1047
38    1048
39    3107
44    3114
45    1077
52    1842
54    1861
75    1131
77    1115
93    1841
94    1855
Name: user_id, dtype: int64

In [ ]:
# P5.2


count         22
unique         3
top       FEMALE
freq          16
Name: gender, dtype: object

In [ ]:
#P5.3


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


user_id  institution_id  age  gender  scores
0      1128               9   18    MALE      14
1      1050               7   16  FEMALE      16
2       986               1   17  FEMALE      13
3       987               1   16  FEMALE      19
4       988               1   16  FEMALE      17
..      ...             ...  ...     ...     ...
93     1841               2   17  FEMALE      18
94     1855               2   17  FEMALE      20
95     1096               7   20    MALE      19
96     1878               2   17    MALE      12
97     2875               4   16  FEMALE      12

[98 rows x 5 columns]

## Pergunta 6

Execute o comando

```python
dfx.describe()
```
e descreva o resultado e a sua utilidade, após investigar o que esta função do Pandas devolve.

In [ ]:
dfx.describe()

user_id  institution_id        age
count    98.000000       98.000000  98.000000
mean   1830.428571        5.193878  16.132653
std     836.381443        2.775661   3.862689
min     986.000000        1.000000   3.000000
25%    1077.500000        2.000000  16.000000
50%    1838.500000        4.000000  16.000000
75%    2855.750000        7.750000  17.000000
max    3127.000000        9.000000  30.000000